flexix_prototype_controller_prototype:
    resource: "@FlexixPrototypeBundle/Resources/config/routing/entity.yml"
    prefix:   /



test:
    path: "test1"
    defaults: { _controller: "flexix_prototype_controller.test_controller:testAction", state: "",  format: ~ }
    methods:  [GET, POST]
    options:
        expose: true 
        
