list:
    path: "{module}/{alias}/list"
    defaults: { _controller: "flexix_prototype_controller.entity_controller:listAction", "action": "list", format: ~ }
    methods:  [GET, POST]
    options:
        expose: true 
filter:
    path: "{module}/{alias}/filter"
    defaults: { _controller: "flexix_prototype_controller.entity_controller:filterAction", "action": "filter", format: ~ }
    methods:  [GET, POST]
    options:
        expose: true    
        
typeahead:
    path: "{module}/{alias}/typeahead/{field}"
    defaults: { _controller: "flexix_prototype_controller.entity_controller:listAction", "action": "typeahead", format: ~ }
    methods:  [GET, POST]
    options:
        expose: true    
new:
    path: "{module}/{alias}/new"
    defaults: { _controller: "flexix_prototype_controller.entity_controller:newAction", "action": "new",   format: ~ }
    requirements: {"applicationPath":".+" ,"entitiesPath": ".+"}
    methods:  [GET, POST]
    options:
        expose: true        
delete:
    path: "{module}/{alias}/delete/{id}"
    defaults: { _controller: "flexix_prototype_controller.entity_controller:deleteAction", "action": "delete", format: ~,id: '' }
    methods:  [GET,DELETE]
    options:
        expose: true
edit:
    path: "{module}/{alias}/edit/{id}"
    defaults: { _controller: "flexix_prototype_controller.entity_controller:editAction",  "action": "edit", format: ~, id: '' }
    methods:  [GET, POST]
    options:
        expose: true            
get:
    path: "{module}/{alias}/get/{id}"
    defaults: { _controller: "flexix_prototype_controller.entity_controller:getAction","action": "get", format: ~,id: '' }
    methods:  [GET, POST]
    options:
        expose: true